inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'app/channels/**/*'
    - 'config/initializers/**/*'
    - 'config/environments/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'db/migrate/*'

Style/Documentation:
  Exclude:
    - '**/*'

Metrics/LineLength:
  Max: 130
  Exclude:
  